//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceApplication.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int PostUID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Name { get; set; }
        public int AccountFrom { get; set; }
        public string AccountWhere { get; set; }
        public int Total { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
